#1. Primero indicamos la base
FROM ubuntu 
#2. Luego actualizamos el sistema operativo
RUN apt update 
#3. FInalmente instalamos python
RUN apt install python3 -y 

#******* OJO ********
# Este es el comando para crear nuestra propia imagen:
#       docker build --tag ubuntu-python3 .
#       donde:
#               --tag indica el nombre de nuestra nueva imagen
#               y el punto (.) el directorio donde se encuentra nuestro Dockerfile

