# 1. Primeramente descargamos una imagen de jenkins con el siguiente comando
# 	docker pull jenkins/jenkis
#
# 2. Una vez descargado ejecutamos el siguiente comando de docker
#	docker run -d -p 3000:8080 jenkins/jenkins
#	
#	donde:  
#		-d indica que el contenedor debe permanecer vivo
#		-p indica el puerto expuesto y el de la aplicacion
# 		   i.e., -p puerto_expuesto:puerto_aplicacion 
#		   En el ejemplo:
#			docker run -d -p 3000:8080 jenkins/jenkins
#		   Al aplcacion jenkins	trae por default el puerto 8080,
#		   pero al exponerlo en el contenedor se le podra llegar	
#		   a traves del puerto 3000
#
